### ISSUE TITLE
Stack build error on Ubuntu 19.04

### ISSUE THREAD

**Issue by govertbuijs** [facebook/duckling#443]
When trying to build Duckling on Ubuntu, the 'stack build' command exits with an error :
```
/<path>/duckling/Duckling/Types.hs:338:11: error:  
    • Variable not in scope: (<>) :: [Char] -> Text -> t0  
    • Perhaps you meant one of these:  
        ‘<*>’ (imported from Prelude), ‘*>’ (imported from Prelude),  
        ‘>>’ (imported from Prelude)
```
stack --version : Version 2.1.3
ghc --version : ... version 8.4.4

There error (and code) seems to be introduced in commit 7f2450e067cdc122f3ee6fe11f25656a1f7b2387,
the version before that commit compiles and runs fine.

**Comment by haoxuany** [comment]
My bad, this should be fixed with 8d681f7ec7e01968aefa8eead4fbaa41a0826613
Thanks for the catch!
